language: python
python:
  - "2.7"

virtualenv:
  system_site_packages: true

install:
  - sudo pip install -r requirements.txt
  - sudo pip install coveralls

script: nosetests --with-coverage --cover-package=energistream-py

after_success:
  - coveralls
